### ISSUE TITLE
Saplings not dropped

### ISSUE THREAD

**Issue by SlimeDog** [ThizThizzyDizzy/tree-feller#63]
Paper 1.19.4-484 and Spigot 1.19.4-3703 (and previously)
TreeFeller 1.21.4 (and previously, at least 1.21.3)

Trees are not dropping saplings. I have
```
replant-saplings: false
use-inventory-saplings: false
spawn-saplings: 2
sapling-timeout: 50
```
and tool-specific `max-saplings` settings (but since `replant-saplings: false` that should be irrelevant). No saplings are spawned as I fell trees. What am I missing?

`config.yml` sans comments, empty lines, and compatibility entries
```
startup-logs: false
default-enabled: true
scan-distance: 256
leaf-detect-range: 6
leaf-break-range: 6
required-logs: 4
required-leaves: 10
max-logs: 250
max-height: 5
allow-partial: false
player-leaves: false
diagonal-leaves: false
ignore-leaf-data: false
require-cross-section: true
force-distance-check: false
banned-logs: 
banned-leaves: 
max-horizontal-trunk-pillar-length: 6
max-trunks: 4
cutting-animation: true
anim-delay: 1
replant-saplings: false
use-inventory-saplings: false
spawn-saplings: 2
sapling-timeout: 50
grass: 
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    - ROOTED_DIRT
root-distance: 6
log-behavior: FALL_HURT
leaf-behavior: BREAK
fall-hurt-amount: 2.0
fall-hurt-max: 40
directional-fall-behavior: AWAY
overridables: 
    - AIR
    - CAVE_AIR
    - FERN
    - GRASS
    - LARGE_FERN
    - SEAGRASS
    - TALL_GRASS
    - TALL_SEAGRASS
    - WATER
lock-fall-cardinal: false
directional-fall-velocity: 0.45
vertical-fall-velocity: 0.05
explosive-fall-velocity: 0.0
random-fall-velocity: 0.15
fall-delay: 2
respect-unbreaking: true
respect-unbreakable: true
damage-mult: 1.0
stacked-tools: false
leaf-fortune: true
leaf-silk-touch: false
log-fortune: true
log-silk-touch: true
leave-stump: true
rotate-logs: true
drop-conversions: 
    OAK_WOOD: OAK_LOG
    SPRUCE_WOOD: SPRUCE_LOG
    BIRCH_WOOD: BIRCH_LOG
    JUNGLE_WOOD: JUNGLE_LOG
    ACACIA_WOOD: ACACIA_LOG
    DARK_OAK_WOOD: DARK_OAK_LOG
    CRIMSON_HYPHAE: CRIMSON_STEM
    WARPED_HYPHAE: WARPED_STEM
block-conversions: 
leaf-drop-chance: 0.0
log-drop-chance: 1.0
global-effects:
    - sawdust
consumed-food-base: 0.0
consumed-food-logs: 0.0
consumed-food-leaves: 0.0
consumed-health-base: 0.0
consumed-health-logs: 0.0
consumed-health-leaves: 0.0
required-enchantments:
banned-enchantments:
min-durability:
max-durability:
min-durability-percent:
max-durability-percent:
prevent-breakage: false
required-lore:
required-name:
required-permissions:
min-time:
max-time:
min-phase:
max-phase:
min-food:
max-food:
min-health:
max-health:
custom-model-data:
enable-adventure: false
enable-survival: true
enable-creative: false
with-sneak: false
without-sneak: true
worlds:
   - world_skyblock
   - world_skyblock_nether
   - world_skyblock_the_end
world-blacklist: true
cooldown:
cascade: false
parallel-cascade-limit: 1
cascade-check-limit: 64
...
tools:
    - { type: WOODEN_AXE, required-permissions: [treefeller.wooden_axe] }
    - { type: STONE_AXE, required-permissions: [treefeller.stone_axe] }
    - { type: IRON_AXE, required-permissions: [treefeller.iron_axe] }
    - { type: GOLDEN_AXE, required-permissions: [treefeller.golden_axe] }
    - { type: DIAMOND_AXE, required-permissions: [treefeller.diamond_axe] }
    - { type: NETHERITE_AXE, required-permissions: [treefeller.netherite_axe] }
    - { type: AIR, required-permissions: [treefeller.air], damageMult: 0.0 }
trees:
    - [[OAK_LOG, OAK_WOOD], OAK_LEAVES, {sapling: OAK_SAPLING, max-saplings: 1}]
    - [[BIRCH_LOG, BIRCH_WOOD], BIRCH_LEAVES, {sapling: BIRCH_SAPLING, max-saplings: 1}]
    - [[SPRUCE_LOG, SPRUCE_WOOD], SPRUCE_LEAVES, {sapling: SPRUCE_SAPLING, max-saplings: 4}]
    - [[JUNGLE_LOG, JUNGLE_WOOD], JUNGLE_LEAVES, {sapling: JUNGLE_SAPLING, max-saplings: 4}]
    - [[DARK_OAK_LOG, DARK_OAK_WOOD], DARK_OAK_LEAVES, {sapling: DARK_OAK_SAPLING, max-saplings: 4}]
    - [[ACACIA_LOG, ACACIA_WOOD], ACACIA_LEAVES, {sapling: ACACIA_SAPLING, max-saplings: 1}]
    - [[OAK_LOG, OAK_WOOD], [AZALEA_LEAVES, FLOWERING_AZALEA_LEAVES], {sapling: [AZALEA, FLOWERING_AZALEA], max-saplings: 1, diagonal-leaves: true}]
    - [[MANGROVE_LOG, MANGROVE_WOOD], [MANGROVE_ROOTS, MANGROVE_LEAVES], {roots: [MANGROVE_ROOTS], sapling: [MANGROVE_PROPAGULE], max-saplings: 1, max-trunks: 16, max-horizontal-trunk-pillar-length: 16, leaf-detect-range: 16, leaf-break-range: 16, required-logs: 3, root-distance: 16, diagonal-leaves: true}]
    - [[CRIMSON_STEM, CRIMSON_HYPHAE], [NETHER_WART_BLOCK, SHROOMLIGHT], {sapling: CRIMSON_FUNGUS, max-saplings: 1, grass: [CRIMSON_NYLIUM], diagonal-leaves: true, leaf-detect-range: 8, leaf-break-range: 8}]
    - [[WARPED_STEM, WARPED_HYPHAE], [WARPED_WART_BLOCK, SHROOMLIGHT], {sapling: WARPED_FUNGUS, max-saplings: 1, grass: [WARPED_NYLIUM], diagonal-leaves: true, leaf-detect-range: 8, leaf-break-range: 8}]
effects:
    - {name: sawdust, chance: 1.0, location: logs, type: particle, particle: poof, dx: 0.5, dy: 0.5, dz: 0.5, speed: .01, count: 10}
```
